name: ramona_store
description: An simple virtual store.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/p1.jpg
    - assets/p2.jpg
    - assets/p3.jpg
    - assets/p4.jpg
    - assets/p5.jpg
    - assets/p6.jpg
  fonts:
    - family: Square
      fonts:
        - asset: fonts/Typo_Square_Light.otf
        - asset: fonts/Typo_Square_Bold.otf
        - asset: fonts/Typo_Square_Regular.otf
